Tomoran/issue26
andaze/WebCorporate pull request #28
Opened 2022-03-08 08:21 UTC by tomoran

2022-03-08 09:12 UTC, nishidai-andaze requested changes

2022-03-08 09:12 UTC, nishidai-andaze commented on themes/andaze/layouts/partials/molecle-news-nav.html
> +<div class="newslist">
独自クラスを排除して同一のtailwindcss に書き直す

2022-03-11 09:03 UTC, nishidai-andaze commented
@tomoran このプルリクを修正しておいてください

2022-03-12 10:25 UTC, tomoran commented
@nishidai-andaze 
独自クラスを排除しておきました。

2022-03-13 22:47 UTC, nishidai-andaze approved these changes

2022-03-13 22:47 UTC, merged