Resolved footer spacing issue
andaze/WebCorporate pull request #330
Opened 2022-06-15 03:32 UTC by ameio

To Do
=============================

- [ ] setup proper space 
- [ ] setup proper line between menu 
- [ ] change font size

2022-06-16 03:09 UTC, ameio commented
@nishidai-andaze 
Please wait 
Dont merge this branch

2022-06-17 05:33 UTC, ameio commented
@nishidai-andaze 
Please merge this request

2022-06-17 07:24 UTC, nishidai-andaze commented
@ameio Thank you, ameio san

Please use draft status if you do not want pull requests to be merged.

2022-06-17 07:27 UTC, nishidai-andaze requested changes
@ameio Please refer to https://tailwindcss.com/docs/font-size#customizing-your-theme to set the font size correctly. The name should be much like tailwindcss.

2022-06-17 13:53 UTC, ameio-developer commented on themes/andaze/assets/css/tailwind.css
> +@layer components {
Please remove this class

And this below for custome size

text-[11px]

2022-06-19 08:40 UTC, nishidai-andaze approved these changes

2022-06-19 08:40 UTC, nishidai-andaze commented on themes/andaze/assets/css/tailwind.css
> +@layer components {
@ameio-developer Thank you very much. The correction has been confirmed.

2022-06-19 08:40 UTC, merged