Update youtube section
andaze/WebCorporate pull request #647
Opened 2022-11-04 07:04 UTC by TomoyukiHata

- [ ] add section to show videos
- [ ] collect and show videos by YouTube Data API
- [ ] apply modalvideo.js

2022-11-10 01:24 UTC, TomoyukiHata commented
YouTubeセクション仕様
・YouTube DATA API でチャンネル動画を取得（最大50動画）
・HUGO の GET REMOTE DATA により JSON データを取得
・Swiperで取得した動画をスライドさせる
・動画サムネイルをクリックするとモーダルが出現（modal-video.js）

※会社説明動画は最初に見せたいトピックと思われるので、Newsセクション部分に配置（変更なし）
　modal-video.js の自動再生が機能しない（たぶんバグ）ので、会社説明動画部分はスクラッチでモーダル実装（変更なし）

2022-11-10 02:30 UTC, nishidai-andaze requested changes
@TomoyukiHata hugo server したがキービジュアルもろとも動かない

2022-11-10 02:30 UTC, nishidai-andaze commented on themes/andaze/assets/js/youtube.js
> +        if ($(".js-modal-video").length) { //クラス名js-modal-videoがあれば以下を実行
@TomoyukiHata jQuery かこれは？ ES スタイルで書き直し

2022-11-10 05:38 UTC, TomoyukiHata commented on themes/andaze/assets/js/youtube.js
> +        if ($(".js-modal-video").length) { //クラス名js-modal-videoがあれば以下を実行
これjQuery専用のプラグインみたいなので実装方法変えます（書き換えるとエラー）
会社概要と同じ実装方法で

2022-11-11 05:36 UTC, TomoyukiHata commented
jQuery から書き換え
良いプラグインが見つからなかったためスクラッチ実装（会社説明動画用のロジックを流用）

2022-11-14 07:24 UTC, nishidai-andaze approved these changes

2022-11-14 07:25 UTC, merged